#Github.io Personal Page

#Site Settings
title: Patrick Parthen - Full Stack Developer / Projectmanager
email: p.parthen@googlemail.com
description: >- # this means to ignore newlines until "baseurl:"
  Patrick Parthen. Personal Portfolio Blog. Full Stack Developer. Projectmanager.
  JS. React. Angular. HTML. CSS. NEXTjs. ExpressJS.
  SQL. Kubernetes. AWS. Java. Python. Headless.
baseurl: "" # the subpath of your site, e.g. /blog
url: https:\\chaotrick42.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chaotrick42
repository: "chaotrick42/chaotrick42.github.io"


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

#Reading Files
# include:
#  - .htaccess
#  - _pages
#  - files
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#encoding: "utf-8"
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

