title: Full Stack Developer / Projectmanager
author: chaotrick42
email: p.parthen@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Portfolio Blog, Patrick Parthen. Full Stack Developer. Projectmanager.
  JS. React. Angular. HTML. CSS. NEXTjs. ExpressJS.
  SQL. Kubernetes. AWS. Java. Python. Headless.

# social links
github_username:  chaotrick42 # DO NOT include the @ character, or else the build will fail!
#Theme
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage